# Generated by Django 3.2.5 on 2021-08-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
