
version: '3'

services:
  server:
    env_file: .env
#    build:
#      context: .
#      dockerfile: Dockerfile
    container_name: ha_college
    command: "python manage.py runserver 0.0.0.0:8000"
    image: ha-college/backend:0.0.1
    volumes:
      - .:/code
    ports:
      - "8020:8000"
