# Generated by Django 3.2.5 on 2021-07-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="institutioninfo",
            table="institution",
        ),
    ]
