# Generated by Django 3.2.5 on 2021-08-04 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_designation_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_designation_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_designation_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'db_table': 'designation',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('photo', models.ImageField(default='default_images/default_profile_pic.png', upload_to='staff_photo/')),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('religion', models.CharField(blank=True, choices=[('H', 'Hinduism'), ('M', 'Muslim'), ('B', 'Buddhism'), ('C', 'Christianity'), ('O', 'Others')], max_length=30, null=True)),
                ('blood_group', models.CharField(choices=[('1', 'A+'), ('2', 'B+'), ('3', 'O+'), ('4', 'A-'), ('5', 'B-'), ('6', 'O-'), ('7', 'AB+'), ('8', 'AB-')], max_length=1)),
                ('pan_no', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_staff_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='staff.designation')),
                ('faculty', models.ManyToManyField(related_name='staff', to='academics.Faculty')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_staff_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_staff_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='StaffAcademicInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('contract_type', models.CharField(choices=[('F', 'FullTime'), ('P', 'PartTime')], max_length=1)),
                ('highest_degree', models.CharField(max_length=50)),
                ('experience', models.FloatField(default=0)),
                ('working_days', models.IntegerField()),
                ('leave', models.FloatField(default=0, help_text="Staff's leave days")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_staffacademicinfo_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_staffacademicinfo_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_staffacademicinfo_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_academic_info', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_academic_info',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('document', models.FileField(upload_to='staff/document_upload/')),
                ('name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_document_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_document_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_document_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.staff')),
            ],
            options={
                'db_table': 'staff_document',
                'ordering': ['-created_on'],
            },
        ),
    ]
