# Generated by Django 3.2.5 on 2021-08-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="blood_group",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="date_of_joining",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="pan_no",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="religion",
        ),
        migrations.RemoveField(
            model_name="staffacademicinfo",
            name="contract_type",
        ),
        migrations.AddField(
            model_name="staff",
            name="marital_status",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "F"), ("O", "Others")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="spouse_name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffacademicinfo",
            name="Faculty",
            field=models.ManyToManyField(
                related_name="staff_academic_info_shift", to="academics.Faculty"
            ),
        ),
        migrations.AddField(
            model_name="staffacademicinfo",
            name="full_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffacademicinfo",
            name="previous_college_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="staffacademicinfo",
            name="previouse_academic_details",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staffacademicinfo",
            name="shift",
            field=models.ManyToManyField(
                related_name="staff_academic_info_faculty", to="academics.Shift"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="staff.designation",
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="faculty",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="staff", to="academics.Faculty"
            ),
        ),
        migrations.AlterField(
            model_name="staffacademicinfo",
            name="experience",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="staffacademicinfo",
            name="highest_degree",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="staffacademicinfo",
            name="leave",
            field=models.FloatField(
                blank=True, default=0, help_text="Staff's leave days", null=True
            ),
        ),
        migrations.AlterField(
            model_name="staffacademicinfo",
            name="working_days",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
