# Generated by Django 3.2.5 on 2021-09-08 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffacademicinfo",
            name="staff",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_academic_info_details",
                to="staff.staff",
            ),
        ),
    ]
