# Generated by Django 3.2.5 on 2021-09-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_staffacademicinfo_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                max_length=1,
                null=True,
            ),
        ),
    ]
