# Generated by Django 3.2.5 on 2021-08-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_alter_staff_spouse_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffacademicinfo",
            old_name="Faculty",
            new_name="faculty",
        ),
    ]
