# Generated by Django 3.2.5 on 2021-08-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_rename_faculty_staffacademicinfo_faculty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="faculty",
        ),
    ]
