# Generated by Django 3.2.5 on 2021-08-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0005_remove_staff_faculty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffacademicinfo",
            old_name="previouse_academic_details",
            new_name="previous_academic_details",
        ),
    ]
