# Generated by Django 3.2.5 on 2021-08-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0007_auto_20210809_0634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffacademicinfo",
            name="previous_email",
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
    ]
