# Generated by Django 3.2.5 on 2021-08-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0008_alter_staffacademicinfo_previous_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffacademicinfo",
            old_name="previous_contact",
            new_name="previous_college_contact",
        ),
        migrations.RenameField(
            model_name="staffacademicinfo",
            old_name="previous_email",
            new_name="previous_college_email",
        ),
    ]
