# Generated by Django 3.2.5 on 2021-08-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0009_auto_20210810_1017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="marital_status",
            field=models.CharField(
                choices=[("M", "Married"), ("S", "Single")], max_length=1
            ),
        ),
    ]
