# Generated by Django 3.2.5 on 2021-08-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0011_auto_20210825_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffacademicinfo",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_academic_info",
                to="staff.designation",
            ),
        ),
    ]
