# Generated by Django 3.2.5 on 2021-08-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0012_alter_staffacademicinfo_designation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffacademicinfo",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="staffacademicinfo",
            name="highest_degree",
        ),
        migrations.RemoveField(
            model_name="staffacademicinfo",
            name="leave",
        ),
        migrations.RemoveField(
            model_name="staffacademicinfo",
            name="previous_college_contact",
        ),
        migrations.RemoveField(
            model_name="staffacademicinfo",
            name="previous_college_email",
        ),
        migrations.RemoveField(
            model_name="staffacademicinfo",
            name="working_days",
        ),
    ]
