# Generated by Django 3.2.5 on 2021-08-27 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_delete_onlineclassinfo"),
        ("staff", "0013_auto_20210826_0607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department",
                to="academics.faculty",
            ),
        ),
    ]
