# Generated by Django 3.2.5 on 2021-09-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0003_auto_20210901_0625"),
    ]

    operations = [
        migrations.AddField(
            model_name="feesetup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feesetup",
            name="due_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="feesetup",
            name="due_type",
            field=models.CharField(
                blank=True,
                choices=[("Prior", "Prior"), ("After", "After")],
                max_length=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feesetup",
            name="fee_type",
            field=models.CharField(
                choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                default="Monthly",
                max_length=31,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feesetup",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
