# Generated by Django 3.2.5 on 2021-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0004_auto_20210909_1117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feesetup",
            name="due_day",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
