# Generated by Django 3.2.5 on 2021-09-10 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("student", "0005_studentinfo_status"),
        ("fees", "0006_feeconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Last modified at"
                    ),
                ),
                ("issued_date", models.DateField()),
                (
                    "total_amount_to_pay",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "discount_in",
                    models.CharField(
                        blank=True,
                        choices=[("P", "Percentage"), ("A", "Amount")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "total_paid_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Cash"), ("bank-transfer", "Bank Transfer")],
                        max_length=31,
                    ),
                ),
                ("narration", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees_feecollection_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "fine",
                    models.ManyToManyField(
                        blank=True, related_name="fee_collection", to="fees.FineType"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees_feecollection_general_info",
                        to="core.institutioninfo",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees_feecollection_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "student_academic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_collection",
                        to="student.studentacademicdetail",
                    ),
                ),
            ],
            options={
                "db_table": "fee_collection",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="StudentPaidFeeSetup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Last modified at"
                    ),
                ),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("due_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees_studentpaidfeesetup_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "fee_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_paid_fee_setup",
                        to="fees.feecollection",
                    ),
                ),
                (
                    "fee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_paid_fee_setup",
                        to="fees.feesetup",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees_studentpaidfeesetup_general_info",
                        to="core.institutioninfo",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees_studentpaidfeesetup_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
            ],
            options={
                "db_table": "student_paid_fee_setup",
                "ordering": ["-created_on"],
            },
        ),
    ]
