# Generated by Django 3.2.5 on 2021-09-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_delete_onlineclassinfo"),
        ("fees", "0007_feecollection_studentpaidfeesetup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentpaidfeesetup",
            name="fee_type",
        ),
        migrations.AddField(
            model_name="studentpaidfeesetup",
            name="fee_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of fee config student paid",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_paid_fee_setup",
                to="fees.feeconfig",
            ),
        ),
        migrations.AlterField(
            model_name="feecollection",
            name="discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Discount amount or percentage",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feecollection",
            name="issued_date",
            field=models.DateField(help_text="Date when student paid fee"),
        ),
        migrations.AlterField(
            model_name="feecollection",
            name="total_amount_to_pay",
            field=models.DecimalField(
                decimal_places=2, help_text="Amount student need to pay", max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="feecollection",
            name="total_paid_amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Total amount student paid", max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="feeconfig",
            name="subject_group",
            field=models.ForeignKey(
                help_text="Fee applied to particular subject group",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_config",
                to="academics.subjectgroup",
            ),
        ),
        migrations.AlterField(
            model_name="feesetup",
            name="fee_type",
            field=models.CharField(
                blank=True,
                choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                max_length=31,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentpaidfeesetup",
            name="fee_collection",
            field=models.ForeignKey(
                help_text="Master fee collection",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_paid_fee_setup",
                to="fees.feecollection",
            ),
        ),
    ]
