# Generated by Django 3.2.5 on 2021-09-17 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("fees", "0010_auto_20210915_1017"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPaidFeeSetupUpdateLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Last modified at"
                    ),
                ),
                (
                    "previous_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "updated_amount",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees_studentpaidfeesetupupdatelog_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees_studentpaidfeesetupupdatelog_general_info",
                        to="core.institutioninfo",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fees_studentpaidfeesetupupdatelog_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "paid_fee_setup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_paid_fee_setup_update_log",
                        to="fees.studentpaidfeesetup",
                    ),
                ),
            ],
            options={
                "db_table": "student_paid_fee_setup_update_log",
                "ordering": ["-created_on"],
            },
        ),
    ]
