# Generated by Django 3.2.5 on 2021-08-04 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=60)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_academicsession_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_session', to='academics.grade')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_academicsession_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_academicsession_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'db_table': 'Academic Session',
                'ordering': ['-created_on'],
            },
        ),
    ]
