# Generated by Django 3.2.5 on 2021-08-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_delete_onlineclassinfo"),
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicsession",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_session",
                to="academics.faculty",
            ),
        ),
    ]
