# Generated by Django 3.2.5 on 2021-08-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timetable",
            options={"ordering": ["-created_on"]},
        ),
    ]
