# Generated by Django 3.2.5 on 2021-08-04 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guardian', '0001_initial'),
        ('academics', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_studentcategory_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_studentcategory_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_studentcategory_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'db_table': 'students_category',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('admission_number', models.CharField(max_length=20)),
                ('temporary_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(blank=True, choices=[('1', 'A+'), ('2', 'B+'), ('3', 'O+'), ('4', 'A-'), ('5', 'B-'), ('6', 'O-'), ('7', 'AB+'), ('8', 'AB-')], max_length=1, null=True)),
                ('religion', models.CharField(blank=True, choices=[('H', 'Hinduism'), ('M', 'Muslim'), ('B', 'Buddhism'), ('C', 'Christianity'), ('O', 'Others')], max_length=1, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('photo', models.ImageField(upload_to='student-photos/')),
                ('marital_status', models.CharField(choices=[('M', 'Married'), ('S', 'Single')], max_length=1)),
                ('spouse_name', models.CharField(blank=True, max_length=20, null=True)),
                ('disable', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_studentinfo_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('guardian_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='guardian.studentguardianinfo')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_studentinfo_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_studentinfo_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('student_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='student.studentcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_students_admission',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('document', models.FileField(upload_to='student/document/')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_studentdocument_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_studentdocument_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_studentdocument_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_document', to='student.studentinfo')),
            ],
            options={
                'db_table': 'student_document',
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_academic_detail', to='general.academicsession')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_studentacademicdetail_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_academic', to='academics.faculty')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_detail', to='academics.grade')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_studentacademicdetail_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_studentacademicdetail_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_academic_detail', to='academics.section')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_academic', to='academics.shift')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_academic_detail', to='student.studentinfo')),
            ],
            options={
                'db_table': 'student_academic',
            },
        ),
        migrations.CreateModel(
            name='PreviousAcademicDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('last_school', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_previousacademicdetail_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_previousacademicdetail_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_previousacademicdetail_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_academic_detail', to='student.studentinfo')),
            ],
            options={
                'db_table': 'previous_academic_info',
            },
        ),
    ]
