# Generated by Django 3.2.5 on 2021-08-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210805_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='phone',
        ),
    ]
