# Generated by Django 3.2.5 on 2021-08-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_studentinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousacademicdetail',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='previousacademicdetail',
            name='last_school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
