# Generated by Django 3.2.5 on 2021-08-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_auto_20210731_1434"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentinfo",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("1", "A+"),
                    ("2", "B+"),
                    ("3", "O+"),
                    ("4", "A-"),
                    ("5", "B-"),
                    ("6", "O-"),
                    ("7", "AB+"),
                    ("8", "AB-"),
                ],
                default="1",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentinfo",
            name="religion",
            field=models.CharField(
                choices=[
                    ("H", "Hinduism"),
                    ("M", "Muslim"),
                    ("B", "Buddhism"),
                    ("C", "Christianity"),
                    ("O", "Others"),
                ],
                default="H",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
