# Generated by Django 3.2.5 on 2021-08-02 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0001_initial"),
        ("student", "0004_auto_20210802_0719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "A+"),
                    ("2", "B+"),
                    ("3", "O+"),
                    ("4", "A-"),
                    ("5", "B-"),
                    ("6", "O-"),
                    ("7", "AB+"),
                    ("8", "AB-"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="guardian_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_info",
                to="guardian.studentguardianinfo",
            ),
        ),
        migrations.AlterField(
            model_name="studentinfo",
            name="religion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("H", "Hinduism"),
                    ("M", "Muslim"),
                    ("B", "Buddhism"),
                    ("C", "Christianity"),
                    ("O", "Others"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
