# Generated by Django 3.2.5 on 2021-08-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210825_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='status',
            field=models.CharField(choices=[('A', 'Admitted'), ('D', 'Draft')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
