# Generated by Django 3.2.5 on 2021-09-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_studentinfo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentinfo",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="student-photos/"),
        ),
    ]
