# Generated by Django 3.2.5 on 2021-07-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="role",
            name="title",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Administrator", "Administrator"),
                    ("Teacher", "Teacher"),
                    ("Parent", "Parent"),
                    ("Front Desk Officer", "Front Desk Officer"),
                ],
                max_length=63,
            ),
        ),
        migrations.AlterField(
            model_name="systemuser",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
