# Generated by Django 3.2.5 on 2021-07-28 07:29

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20210728_0725"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="systemuser",
            managers=[
                ("objects", user.models.SystemUserManager()),
            ],
        ),
    ]
