# Generated by Django 3.2.5 on 2021-08-04 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_faculty_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_faculty_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academics_faculty_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'db_table': 'academics_faculty',
                'unique_together': {('name', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(choices=[('11', 'Eleven'), ('12', 'Twelve')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_grade_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_grade_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academics_grade_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'db_table': 'academics_grade',
                'unique_together': {('name', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_section_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_section_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academics_section_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'db_table': 'academics_section',
                'unique_together': {('name', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=50)),
                ('credit_hour', models.FloatField()),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_type', models.CharField(choices=[('1', 'Theory'), ('2', 'Theory and Practical')], max_length=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_subject_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_subject_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academics_subject_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'db_table': 'academics_subjects',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day'), ('Evening', 'Evening'), ('Extra', 'Extra')], max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_shift_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_shift', to='academics.faculty')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_shift_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academics_shift_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
            ],
            options={
                'db_table': 'academics_shift',
                'unique_together': {('name', 'institution')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_class_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_faculty', to='academics.faculty')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_grade', to='academics.grade')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_class_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academics_class_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('section', models.ManyToManyField(blank=True, related_name='class_section', to='academics.Section')),
            ],
            options={
                'db_table': 'academics_class',
            },
        ),
        migrations.CreateModel(
            name='ApplyShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_applyshift_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_shift', to='academics.faculty')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_shift', to='academics.grade')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_applyshift_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academics_applyshift_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('section', models.ManyToManyField(blank=True, related_name='apply_shift', to='academics.Section')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_shift', to='academics.shift')),
            ],
            options={
                'db_table': 'academic_apply_shift',
            },
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_subjectgroup_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_group', to='academics.faculty')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_group', to='academics.grade')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_subjectgroup_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academics_subjectgroup_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('section', models.ManyToManyField(blank=True, related_name='subject_group', to='academics.Section')),
                ('subject', models.ManyToManyField(related_name='subjects', to='academics.Subject')),
            ],
            options={
                'db_table': 'academic_subject_group',
                'unique_together': {('name', 'institution')},
            },
        ),
    ]
