# Generated by Django 3.2.5 on 2021-08-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyshift',
            name='section',
        ),
        migrations.AddField(
            model_name='applyshift',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_shift', to='academics.section'),
            preserve_default=False,
        ),
    ]
