# Generated by Django 3.2.5 on 2021-08-10 06:03

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_auto_20210809_1054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applyshift',
            unique_together={('shift', 'grade', 'section', 'faculty', 'institution')},
        ),
        migrations.CreateModel(
            name='OnlineClassInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last modified at')),
                ('title', models.CharField(max_length=255)),
                ('class_date', models.DateField(blank=True, null=True)),
                ('days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'MON'), ('2', 'TUE'), ('3', 'WED'), ('4', 'THU'), ('5', 'FRI'), ('6', 'SAT'), ('7', 'SUN')], max_length=1), blank=True, default=list, null=True, size=None)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('link', models.CharField(max_length=253)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlineclass_academic_session', to='general.academicsession')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_onlineclassinfo_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlineclass_faculty', to='academics.faculty')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlineclass_grade', to='academics.grade')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academics_onlineclassinfo_general_info', to='core.institutioninfo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academics_onlineclassinfo_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified by')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onlineclass_section', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlineclass_subject', to='academics.subject')),
            ],
            options={
                'db_table': 'online_class',
                'ordering': ['-created_on'],
            },
        ),
    ]
