# Generated by Django 3.2.5 on 2021-07-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="name",
            field=models.CharField(
                choices=[("11", "Eleven"), ("12", "Twelve")], max_length=20
            ),
        ),
    ]
