# Generated by Django 3.2.5 on 2021-07-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_auto_20210728_0724"),
        ("academics", "0003_auto_20210729_0714"),
    ]

    operations = []
