# Generated by Django 3.2.5 on 2021-07-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_grade_name"),
        ("academics", "0004_merge_0003_auto_20210728_0724_0003_auto_20210729_0714"),
    ]

    operations = []
