# Generated by Django 3.2.5 on 2021-08-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_auto_20210810_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
