# Generated by Django 3.2.5 on 2021-08-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0005_subject_is_optional"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OnlineClassInfo",
        ),
    ]
