# Generated by Django 3.2.5 on 2021-07-31 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_alter_institutioninfo_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecondaryGuardianInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Last modified at"
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("F", "Father"),
                            ("M", "Mother"),
                            ("B", "Brother"),
                            ("S", "Sister"),
                            ("R", "Relative"),
                        ],
                        max_length=1,
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("phone", models.CharField(db_index=True, max_length=15)),
                (
                    "photo",
                    models.ImageField(
                        default="default_images/default_profile_pic.png",
                        upload_to="secondary_guardian/images",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_secondaryguardianinfo_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_secondaryguardianinfo_general_info",
                        to="core.institutioninfo",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_secondaryguardianinfo_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
            ],
            options={
                "db_table": "secondary_guardians_info",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="StudentGuardianInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Last modified at"
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=15, unique=True)),
                ("occupation", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        default="default_images/default_profile_pic.png",
                        upload_to="parent/images",
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("F", "Father"),
                            ("M", "Mother"),
                            ("B", "Brother"),
                            ("S", "Sister"),
                            ("R", "Relative"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_studentguardianinfo_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_studentguardianinfo_general_info",
                        to="core.institutioninfo",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guardian_studentguardianinfo_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "secondary_guardian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_secondary_guardian",
                        to="guardian.secondaryguardianinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_guardian_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "students_guardian_info",
                "ordering": ["-created_on"],
            },
        ),
    ]
